export default {
  ERROR: 'ERROR_POPUP',
  INFO: 'INFO_POPUP',
  CONFIRM: 'CONFIRM_POPUP',
  CREATE_MODEL_CANCEL_CONFIRM: 'CREATE_MODEL_CANCEL_CONFIRM_POPUP',
  CREATE_MODEL_SUCCESS: 'CREATE_MODEL_SUCCESS_POPUP',
  CREATE_MODEL_ERROR: 'CREATE_MODEL_ERROR_POPUP',
};
