export const SET_CONNECTIONS = 'CREATE_CONNECTIONS::SET_CONNECTIONS';
export const CREATE_START = 'CREATE_CONNECTIONS::CREATE_START';
export const CREATE_SUCCESS = 'CREATE_CONNECTIONS::CREATE_SUCCESS';
export const CREATE_FAILURE = 'CREATE_CONNECTIONS::CREATE_FAILURE';

export const HOST_VALUE = 'CREATE_CONNECTIONS::HOST_VALUE';
export const PORT_VALUE = 'CREATE_CONNECTIONS::PORT_VALUE';
export const NAME_DB_VALUE = 'CREATE_CONNECTIONS::NAME_DB_VALUE';
export const NAME_CONNECTION_VALUE = 'CREATE_CONNECTIONS::NAME_СONNECTION_VALUE';
export const USERNAME_VALUE = 'CREATE_CONNECTIONS::USERNAME_VALUE';
export const PASSWORD_VALUE = 'CREATE_CONNECTIONS::PASSWORD_VALUE';
export const TYPE_VALUE = 'CREATE_CONNECTIONS::TYPE_VALUE';
export const EMPTY_FIELDS_ERROR = 'CREATE_CONNECTIONS::EMPTY_FIELDS_ERROR';
export const APPEND_CONNECTIONS = 'CREATE_CONNECTIONS::APPEND_CONNECTIONS';
