export const USERNAME_INPUT_VALUE = 'LOGIN::USERNAME_INPUT_VALUE';
export const PASSWORD_INPUT_VALUE = 'LOGIN::PASSWORD_INPUT_VALUE';
export const CLEAR_PASSWORD_VALUE = 'LOGIN::CLEAR_PASSWORD_VALUE';
export const FORM_SUBMIT = 'LOGIN::FORM_SUBMIT';
