export const SELECT_MODEL = 'CREATE_REPORT::SELECT_MODEL';
export const DESELECT_MODEL = 'CREATE_REPORT::DESELECT_MODEL';
export const FETCH_MODELS_FOR_REPORT_START = 'CREATE_REPORT::FETCH_MODELS_FOR_REPORT_START';
export const FETCH_MODELS_FOR_REPORT_ERROR = 'CREATE_REPORT::FETCH_MODELS_FOR_REPORT_ERROR';
export const FETCH_MODEL_FOR_REPORT_SUCCESS = 'CREATE_REPORT::FETCH_MODEL_FOR_REPORT_SUCCESS';
